# Configuration for the web admin and CRL servers
web:
  host: 'localhost'
  port: 80
  crl: 'http://localhost/ca.crl'
  # The admin is used to create, sign and revoke certificates
  admin: 
    allowed_ips: [ '192.168.0.1', '127.0.0.1' ] # Comma separated list of IP addresses that are allowed to access the web admin

privileges:
  user: 'phill'
  group: 'staff'
  
certificate:
  years: 1
# Configuration relating to certificate authority
ca:
  root:
    country: 'GB'
    state: 'West Midlands'
    locality: 'Birmingham'
    organisation: "Phill's Root CA"
    cn: "Phill's Root Certificate Authority"
    years: 20
  intermediate:
    country: 'GB'
    state: 'West Midlands'
    locality: 'Birmingham'
    organisation: "Phill's Intermediate CA"
    cn: "Phill's Intermediate Certificate Authority"
    years: 20