#!/usr/bin/env ruby
puts ENV['APP_ENV']

# Set our root dir
$:.unshift(File.join(File.expand_path(File.dirname(__FILE__)), '.'))
$root_dir = File.expand_path('..', __FILE__)

# Load and bootstrap RubyCA
require 'core/load'
require 'core/bootstrap'
require 'core/ca/setup'
require 'core/web/server'
require 'core/web/flash'

if __FILE__ == $0 then
  # If not first_run_complete exists, then it is the first run. Perform setup.
  unless RubyCA::Core::Models::Config.find(name: 'first_run_complete')
    first_run_setup
  end
end

# Start server
if $config['web']['port'] < 1024
  unless Process.euid == 0 
    puts "\nError:" 
    puts "RubyCA is configured to use ports under 1024. Root access is required."
    puts "Once the server bind configured port, root rights will be reduced to regular user privileges.\n\n"
    puts "Please execute RubyCA with the command \"sudo ./RubyCA\""
    puts "or modify the configuration file to set a port greater than 1024.\n\n"
    abort
  end
end

RubyCA::Core::Web::Server.run!
puts ''